name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ruby_version: [3.2, 3.3, 3.4]
      fail-fast: false
    runs-on: ubuntu-latest
    name: Test on Ruby ${{ matrix.ruby_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec
